# version: '3'

 
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    ports:
      - ":80"
    depends_on:
      - app
    container_name: nginx-${APP_NAME}

  
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./:/var/www

    container_name: app-${APP_NAME}

 


 
   
